# Generated by Django 6.0.2 on 2026-02-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('NAM', 'Numericko-analytické myšlení'), ('UAJ', 'Uvažování v anglickém jazyce'), ('KM', 'Kritické myšlení')], max_length=10)),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Lehká'), ('medium', 'Střední'), ('hard', 'Těžká')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
            ],
            options={
                'verbose_name': 'Otázka',
                'verbose_name_plural': 'Otázky',
                'ordering': ['dimension', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question')),
            ],
            options={
                'verbose_name': 'Odpověď',
                'verbose_name_plural': 'Odpovědi',
                'ordering': ['order'],
            },
        ),
    ]
