# Generated by Django 6.0.2 on 2026-02-20 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='test',
        ),
        migrations.AddField(
            model_name='testattempt',
            name='question_ids',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='attempt_type',
            field=models.CharField(choices=[('test', 'Test')], default='test', max_length=20),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.CreateModel(
            name='QuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('last_visited', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postup u otázky',
                'verbose_name_plural': 'Postup u otázek',
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.DeleteModel(
            name='PracticeTest',
        ),
    ]
