# Generated by Django 6.0.2 on 2026-02-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_remove_testattempt_test_testattempt_question_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
